CC:=gcc

# system:system_test.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@

# fork_test:fork_test.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@

# fork_fd_test:fork_fd_test.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@

# erlou:erlou.c
# 	-${CC} -o $@ $^

# execve_test:execve_test.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@
# fork_execve_test:fork_execve_test.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@

# waitpid_test:waitpid_test.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@
# prstree:prstree.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@
# unnamed_pipe_test:unnamed_pipe_test.c
# 	-${CC} -o $@ $^
# 	-./$@ "test"
# 	-rm ./$@

# fifo_write:fifo_write.c
# 	-${CC} -o $@ $^
# fifo_read:fifo_read.c
# 	-${CC} -o $@ $^

# shard_memory:shard_memory.c
# 	-${CC} -o $@ $^
# 	-./$@ 
# 	-rm ./$@

# father_son:father_son_mq_test.c
# 	-${CC} -o $@ $^
# 	-./$@ 
# 	-rm ./$@

# producer:producer.c
# 	-${CC} -o $@ $^

consumer:consumer.c
	-${CC} -o $@ $^