CC:=gcc

# create_test:create_test.c
# 	${CC} -o $@ $^
# 	./$@
# 	rm ./$@

# terminate_test:terminate_test.c
# 	${CC} -o $@ $^
# 	./$@
# 	rm ./$@

# race_condition_test:race_condition_test.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@

# rwlock_test:rwlock_test.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@
# rwlock_hungry_solved:rwlock_hungry_solved.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@

# condition_var:condition_var.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@

# unnamed_Sem:unnamed_Sem.c
# 	-${CC} -o $@ $^
# 	-./$@
# 	-rm ./$@
# unnamed_sem_bin_process_condition: unnamed_sem_bin_process_condition.c
# 	-$(CC) -o $@ $^
# 	-./$@
# 	-rm ./$@

# unnamed_sem_bin_process: unnamed_sem_bin_process.c
# 	-$(CC) -o $@ $^
# 	-./$@
# 	-rm ./$@
# unnamed_sem_bin_process_isolate: unnamed_sem_bin_process_isolate.c
# 	-$(CC) -o $@ $^
# 	-./$@
# 	-rm ./$@
# unnamed_sem_count_thread: unnamed_sem_count_thread.c
# 	-$(CC) -o $@ $^
# 	-./$@
# 	-rm ./$@
unnamed_sem_count_process: unnamed_sem_count_process.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@